services:
  postgres:
    image: postgres:15
    container_name: cinema-postgres
    environment:
      POSTGRES_DB: iis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itdep
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: cinema-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/sessions"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/iis
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: itdep

  frontend:
    build: ./frontend-react
    container_name: cinema-frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_API_URL: http://localhost:8080/api

  frontend-angular:
    build: ./frontend-angular
    container_name: cinema-frontend-angular
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres-data: